services:
  jaeger:
    image: "jaegertracing/jaeger:2.14.1"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "16686:16686"
      - "4318:4318"

  mysql:
    image: "mysql:8.0"
    environment:
      - "MYSQL_ROOT_PASSWORD=root_password"
      - "MYSQL_DATABASE=clean-arch-go"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data:
