services:
  jaeger:
    image: "jaegertracing/all-in-one:1.65.0"
    ports:
      - "16686:16686"
      - "14268:14268"
  mysql:
    image: "mysql:8.4.4-oraclelinux9"
    environment:
      - "MYSQL_ROOT_PASSWORD=root_password"
      - "MYSQL_DATABASE=task"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=user_password"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data:
