// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Task defines model for Task.
type Task struct {
	AssignedTo openapi_types.UUID `json:"assignedTo"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  openapi_types.UUID `json:"createdBy"`
	Status     string             `json:"status"`
	Title      string             `json:"title"`
	UpdatedAt  time.Time          `json:"updatedAt"`
	Uuid       openapi_types.UUID `json:"uuid"`
}
