openapi: "3.0.0"
info:
  version: 1.0.0
  title: Task Manager

paths:
  /tasks:
    get:
      operationId: getTasks
      responses:
        "200":
          description: todo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: createTask
      requestBody:
        description: todo
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostTask"
      responses:
        "201":
          description: todo
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tasks/{taskId}/assign:
    post:
      operationId: assignTask
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Assign task to a user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssignTask"
      responses:
        "200":
          description: Task successfully assigned
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    Task:
      type: object
      required:
        [uuid, title, status, createdBy, assignedTo, createdAt, updatedAt]
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          example: Mariusz Pudzianowski
        status:
          type: string
          example: todo
        createdBy:
          type: string
          format: uuid
        assignedTo:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PostTask:
      type: object
      required: [title, creator]
      properties:
        title:
          type: string
          example: "let's do leg day!"
        creator:
          type: string
          format: uuid
    AssignTask:
      type: object
      required: [taskId, assigner, assignee]
      properties:
        taskId:
          type: string
          format: uuid
        assigner:
          type: string
          format: uuid
        assignee:
          type: string
          format: uuid
