openapi: "3.0.0"
info:
  version: 1.0.0
  title: Task Manager
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  - bearerAuth: []
paths:
  /tasks:
    get:
      operationId: getTasks
      responses:
        "200":
          description: todo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      required:
        [uuid, title, status, createdBy, assignedTo, createdAt, updatedAt]
      properties:
        uuid:
          type: string
          format: uuid
        title:
          type: string
          example: Mariusz Pudzianowski
        status:
          type: string
          example: todo
        createdBy:
          type: string
          format: uuid
        assignedTo:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
